### ISSUE TITLE
Unity 2022.3.27f1 / SQLite-net 1.0.0-preview10 — DllNotFoundException

### ISSUE THREAD

**Issue by SergeyBaryshev** [gilzoide/unity-sqlite-net#11]
Hello Gil!
I have simple method in Unity project:
```
private SQLiteConnection CreateDatabase()
{
	var db = new SQLiteConnection(Path.Combine(Application.persistentDataPath, "Cache.db"), true);
	db.TableChanged += TableChanged;
	db.CreateTable<User>(CreateFlags.ImplicitPK);
	db.CreateTable<OfflineUser>(CreateFlags.ImplicitPK);
	return db;
}
```
On Windows it's works perfectly, but when i build and run on Android, i got this exception on first line of this method:

> DllNotFoundException: gilzoide-sqlite-net assembly:<unknown assembly> type:<unknown type> member:(null)
> SQLite.SQLite3..cctor () (at ./Library/PackageCache/com.gilzoide.sqlite-net@3a952ebe4f/Runtime/SQLiteConfig.Log.cs:33)
> Rethrow as TypeInitializationException: The type initializer for 'SQLite.SQLite3' threw an exception.
> SQLite.SQLiteConnection..ctor (SQLite.SQLiteConnectionString connectionString) (at ./Library/PackageCache/com.gilzoide.sqlite-net@3a952ebe4f/Runtime/sqlite-net/SQLite.cs:292)
> SQLite.SQLiteConnection..ctor (System.String databasePath, System.Boolean storeDateTimeAsTicks) (at ./Library/PackageCache/com.gilzoide.sqlite-net@3a952ebe4f/Runtime/sqlite-net/SQLite.cs:251)

If you need more some specific info, just let me know!

**Comment by gilzoide** [comment]
Hey @SergeyBaryshev, thanks for the report!
It's been some time since I tested this package on Android, maybe something broke from previous versions to the current one 🤔
Maybe you can look into the generated APK or the gradle project (if you are using Unity's default build pipeline, it's in `Library/Bee/Android/Prj/IL2CPP/Gradle`) and check if the `libgilzoide-sqlite-net.so` library is there somewhere at least.
I'll probably look into this over the weekend.

**Comment by gilzoide** [comment]
Thanks for the additional info.
Maybe you have the same problem as #13. If this is the case, I think I know how to fix it. Will keep you posted.

**Comment by gilzoide** [comment]
Hehe, enabling the "debug" logs in logcat showed the error about missing symbols, so the issues seem to be the same. Adding `-lm` to SQLite native build seems to solve this. I'll open a PR fixing this soon.

**Comment by gilzoide** [comment]
Version `1.0.0-preview11` should work on Android now, please let me know if it works for you.
Cheers \o/

**Comment by SergeyBaryshev** [comment]
Hey @gilzoide 
I had checked preview11 and it works like a charm, building with ILL2CPP and Mono.
Thanks for your work!
