### ISSUE TITLE
Unity 2019.4.40f1  Android  ： SQLite-net 1.0.0-preview10 — DllNotFoundException

### ISSUE THREAD

**Issue by RichardsATcn** [gilzoide/unity-sqlite-net#13]
Windows 11 run example success.
but package android  error:

2024/05/16 10:46:12.598 30752 30977 Debug Unity Unable to load library '/data/app/~~k3qegS3QM5QMY4EGtYaDYA==/A00.MFB.DYPY-wWHCn8tqlYuv5KY9ODpvrA==/lib/arm64/libgilzoide-sqlite-net.so', native render plugin support disabled: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "acos" referenced by "/data/app/~~k3qegS3QM5QMY4EGtYaDYA==/A00.MFB.DYPY-wWHCn8tqlYuv5KY9ODpvrA==/lib/arm64/libgilzoide-sqlite-net.so"...

![image](https://github.com/gilzoide/unity-sqlite-net/assets/8119891/951972c9-b40e-4b42-94f8-3c7ecc3c7fe1)

**Comment by gilzoide** [comment]
Hey @RichardsATcn, thanks for the report!
Hmm, I guess we the native build is missing the link of the math library. Should be easy to fix, I'll look into it possibly this weekend.

**Comment by gilzoide** [comment]
This is the same issue as #11.

**Comment by gilzoide** [comment]
Version `1.0.0-preview11` should work on Android now, please let me know if it works for you.
Cheers \o/
