### ISSUE TITLE
Error CS0234 - The type or namespace name does not exist in the namespace (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by Madatek** [gilzoide/unity-sqlite-net#29]
I installed using the Package Manager as specified in the readme file, am I missing something? Thanks!

**Comment by gilzoide** [comment]
Hey @Madatek. Which "type or namespace name" does not exist? Can you show a code sample where that error is showing? Which platform are you using (Windows/Linux/macOS...)? Is the error present in editor or only on builds?

**Comment by Madatek** [comment]
Hello @gilzoide ! I actually solved, I needed to install SQLite from NuGet. Visual Studio was trying to get a Unity subdependancy, I can't even remember what it was anymore, I think it was under Unity.VisualScripting... Doesn't matter though, after installing SQLite from NuGet it works now. Thanks and have a good day!

**Comment by gilzoide** [comment]
Hey @Madatek. You should not need to install anything else for this package to work, most definitely not from NuGet (which, unfortunately, is still non-standard for Unity apps).

> I think it was under Unity.VisualScripting
