### ISSUE TITLE
Linux only support x86_64?

### ISSUE THREAD

**Issue by Hoper-Q** [gilzoide/unity-sqlite-net#31]
Hello! I found there is x86_64 in Linux, but don`t have ARM.
Can it support the ARM architecture for Linux?

**Comment by gilzoide** [comment]
Hey @Hoper-Q, thanks for the report.
I never saw ARM architecture for native plugins on Linux, what version of Unity are you using, Unity 6? I usually test stuff on Unity 2022. I'll check it out later.
But sure, adding support for ARM is an easy feat, just need to build the corresponding native library and setting it up in Unity.

**Comment by gilzoide** [comment]
Hey @Hoper-Q , even Unity 6 doesn't support Linux ARM, check out these docs: https://docs.unity3d.com/6000.0/Documentation/Manual/system-requirements.html

Also, I can't find ARM architecture on native plugins for Linux, even on the latest version, Unity 6000.0.28.

<img width="394" alt="Screenshot 2024-11-22 at 07 48 03" src="https://github.com/user-attachments/assets/ffb5a1d9-a071-4a15-9c5f-3b0367747ecd">

Therefore, I can't add support for ARM if Unity itself doesn't support it. I'll be closing this issue, whenever Unity starts supporting Linux ARM we can make it happen.
