### ISSUE TITLE
SQLiteException: No such table (WebGL)

### ISSUE THREAD

**Issue by stelabouras** [gilzoide/unity-sqlite-net#32]
Let me start by saying thank you for this amazing asset!

I am trying to get my game project to work in WebGL and even though I have integrated this asset and it works fine in the Unity Editor, in the WebGL target I am getting the following error:

> SQLiteException: no such table: TABLENAME

Where `TABLENAME` is the name of my table. The query I am trying to execute is something like the one below (I have also tried the same query without adding double-quotes around the TABLENAME):

```c#
dbc.Query<Result> ("select result from \"TABLENAME\" where number = " + randomNumber);
```

During startup, I check for the database existence in the `Application.persistentDataPath` directory and if it's not there (aka first run) I am executing the following code to fetch it from the `Application.streamingAssetsPath` and then I am copying it to the `persistentDataPath` (as per Unity's [documentation](https://docs.unity3d.com/6000.0/Documentation/Manual/StreamingAssets.html)):

```c#
var filePath = System.IO.Path.Combine(Application.persistentDataPath, dbName);
var streamingPath = System.IO.Path.Combine(Application.streamingAssetsPath, dbName);

UnityWebRequest request = UnityWebRequest.Get(streamingPath);
UnityWebRequestAsyncOperation operation = request.SendWebRequest();

while (!operation.isDone)
{ 
    await Task.Yield(); 
}

if (request.result == UnityWebRequest.Result.Success)
{
    File.WriteAllBytes(filePath, request.downloadHandler.data);
}
else
{
    Debug.LogError("Cannot load file at " + streamingPath);
}
```

I then open the database:

```c#
_dbc = new SQLiteConnection(filePath);
```

I am running Unity 2021.3.31f1 and version 1.1.0 of this asset that includes the recently merged idbvfs change.

Am I missing a critical step here in terms of the WebGL setup? I am also calling the `_dbc.CreateTables();` method right after creating the `SQLiteConnection()` but I don't see any difference.

**Comment by gilzoide** [comment]
> given that I need read-only access to the database

Oh, ok, that's exactly the use case for SQLite database as assets xD

Anyway, thanks for the report, I should definitely add a warning about how files work in idbvfs (both in this package and in idbvfs's repo as well).

Cheers \o/

**Comment by openknowledgesing** [comment]
> > given that I need read-only access to the database
> 
> Oh, ok, that's exactly the use case for SQLite database as assets xD
> 
> Anyway, thanks for the report, I should definitely add a warning about how files work in idbvfs (both in this package and in idbvfs's repo as well).
> 
> Cheers \o/

Hi!Can you give a example how to work in idbvfs ?

**Comment by gilzoide** [comment]
Hey @openknowledgesing. You are asking something that is not exactly about this closed issue, even though related. I'll answer here because it's simpler, but you should open a new Discussion or Issue instead next time.

So, idbvfs is the default VFS on WebGL builds, there's nothing extra that needs to be done. The only caveat about it is that you cannot access the database file itself using File APIs, you can only access the database using SQLite APIs.
```cs
var dbPath = $"{Application.persistentDataPath}/myDatabase.db";

// Access using SQLite-net normally
var db = new SQLiteConnection(dbPath);
db.BeginTransaction();
db.CreateTable<Player>();
db.Insert(new Player { Name = "gilzoide" });
db.Commit();

// CAVEAT: the File API cannot access the underlying file
Debug.Assert(!File.Exists(dbPath));
```
