### ISSUE TITLE
Did this lib support sqlite RTree mode?

### ISSUE THREAD

**Issue by chaoslife** [gilzoide/unity-sqlite-net#4]
Hi, 
Did this lib support sqlite RTree mode on webgl?

**Comment by gilzoide** [comment]
Hi @chaoslife! I'll be honest and say that I'm not sure, but probably yes.
The [SQLite documentation](https://sqlite.org/rtree.html) says that the R\*Tree module source code is included in the amalgamation, which is the source code this package builds. Also, I think none of the [compile flags](https://github.com/gilzoide/unity-sqlite-net/blob/main/Plugins/Makefile#L10-L22) used disable it. I also have no reason to believe the WebGL build would miss any SQLite functionality other than interacting with the filesystem for reading/writing files (in-memory databases should work flawlessly).

**Comment by chaoslife** [comment]
Hi, @gilzoide 
Thank you very much, I will test it recently to see if it works and tell you the result

**Comment by chaoslife** [comment]
Hi, @gilzoide! Is there any webgl connection example? My database is a MemoryStream after downloading from http. Is it possible to convert it and pass it into SQLiteConnection?

**Comment by chaoslife** [comment]
> Hi, @gilzoide! Is there any webgl connection example? My database is a MemoryStream after downloading from http. Is it possible to convert it and pass it into SQLiteConnection?

After my investigation, I found that SQLite does not support this usage scenario. It can only create an empty database in memory, so it should not be a problem.

**Comment by gilzoide** [comment]
Hey @chaoslife.
SQLite itself has seralization functionality, although it is not availably directly in this package.
I did use this serialization in [SQLite Asset](https://github.com/gilzoide/unity-sqlite-asset) package, here's the [related code](https://github.com/gilzoide/unity-sqlite-asset/blob/main/Runtime/SQLiteConnectionExtensions.cs).
I don't remember now why I didn't add the serialization extension methods to this main package and added only there in SQLite Asset, which uses it to save/load databases to/from memory 🤔 I guess it would be more useful to have these here, I'll create an issue about that.
I hope this serialization functionality works for you =]

**Comment by chaoslife** [comment]
> Hey @chaoslife. SQLite itself has seralization functionality, although it is not available directly in this package. I did use this serialization in [SQLite Asset](https://github.com/gilzoide/unity-sqlite-asset) package, here's the [related code](https://github.com/gilzoide/unity-sqlite-asset/blob/main/Runtime/SQLiteConnectionExtensions.cs). I don't remember now why I didn't add the serialization extension methods to this main package and added only there in SQLite Asset, which uses it to save/load databases to/from memory 🤔 I guess it would be more useful to have these here, I'll create an issue about that. I hope this serialization functionality works for you =]

Oh, thank you @gilzoide very much, I will test next week, it's awesome feature!

**Comment by gilzoide** [comment]
FYI, I've added the serialization methods here in #5. Still needs some testing before merging into a new version, but it's already in the repository, so you can try if you want.

**Comment by chaoslife** [comment]
Hey @gilzoide ,
I used the deserialization method to test in the Untiy Editor. The x64 dll reported an error that RTree was not integrated. However, the deserialization method on Win x64 did not report an error. Is it possible to build a dll with RTree and a webgl bc file? I will test again

![image](https://github.com/gilzoide/unity-sqlite-net/assets/2386021/841c7cbf-eac7-4bd4-8191-f6742386cee5)

![image](https://github.com/gilzoide/unity-sqlite-net/assets/2386021/066c65f9-9697-4852-b3ec-ce92ab02098e)

**Comment by gilzoide** [comment]
Ok, so it seems R\*Tree is present in the amalgamation, but not enabled by default (reference: https://www.sqlite.org/compile.html).

I'm not sure now what should be the policy around including modules in the build 🤔 I mean, we can enable R\*Tree alone now, or add other extensions people may use, like FTS5. Enabling R\*Tree, FTS5 and Geopoly makes the build ~400kb bigger, which is quite irrelevant for desktop platforms, but may not be neglible in mobile and web platforms.
It's probably fine though, so I added branch `enable-extensions` and opened #7 with this. Please tell me if this branch works for you, before we merge into main.

**Comment by chaoslife** [comment]
After my test, deserialization and query can be successful on the webgl side, which is great, thank you @gilzoide
