### ISSUE TITLE
How can I use unity-sqlite-net for WebGL in Unity?

### ISSUE THREAD

**Issue by 00Sergio00** [gilzoide/unity-sqlite-net#9]
I'm going to create a small video game that requires me to use a database and be able to import it for Windows, Linux, and WebGL. When I compile the code on Windows, it works as expected, but when I try to compile it on WebGL, I get a compilation error. Is the use of SQLite compatible with WebGL?

**Comment by gilzoide** [comment]
> Is the use of SQLite compatible with WebGL?

Yes, SQLite-net is supported in WebGL builds, just use the latest version (currently `1.0.0-preview9`) and it should work.
Please attach the compilation error to the issue, I can't tell you if there is an actual issue without any more info.

**Comment by 00Sergio00** [comment]
The errors I receive when building for WebGL are as follows:

Error: Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js: undefined symbol: sqlite3_win32_set_directory (referenced by top-level compiled C/C++ code)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Error: Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js: Aborting compilation due to previous errors
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Error: Building Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js failed with output:
wasm-ld: warning: function signature mismatch: sqlite3_config
>>> defined as (i32) -> i32 in Assets/unity-sqlite-net-main/Plugins/lib/webgl/libgilzoide-sqlite-net.bc
>>> defined as (i32, i32) -> i32 in lto.tmp
error: undefined symbol: sqlite3_win32_set_directory (referenced by top-level compiled C/C++ code)
warning: Link with -s LLD_REPORT_UNDEFINED to get more information on undefined symbols
warning: To disable errors for undefined symbols use -s ERROR_ON_UNDEFINED_SYMBOLS=0
warning: _sqlite3_win32_set_directory may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
emcc: error: '"C:/Program Files/Unity/Hub/Editor/2022.3.18f1/Editor/Data/PlaybackEngines/WebGLSupport/BuildTools/Emscripten/node/node.exe" "C:\Program Files\Unity\Hub/Editor/2022.3.18f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\src\compiler.js"
 C:\Users\user\AppData\Local\Temp\tmpshe0erxp.json' failed (returned 1)

Version of Unity I am using: 2022.3.18f1

**Comment by gilzoide** [comment]
All right, thank you for the additional information!

> undefined symbol: sqlite3_win32_set_directory (referenced by top-level compiled C/C++ code)

Hmm, this is weird. I have an idea of what could be happening though, I'll investigate.

> wasm-ld: warning: function signature mismatch: sqlite3_config

This one I've seen in the past, it should be fixed in version `1.0.0-preview9` of the package. Which version of this package are you using?

**Comment by 00Sergio00** [comment]
Wow, that was fast! Now it's working correctly. Thank you for your work.

**Comment by gilzoide** [comment]
> Wow, that was fast!

Well, I've encountered this exact same issue in iOS/Android builds more often than I would like 😂
Knowing the name of the function that's missing, it's usually about either removing the code that references it (in C#, usually a `[DllImport(...)]`) or fixing the native build to include the function.

> Thank you for your work.

No problem, I'm here to help in the way I can ^^
